// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package database

import (
	"context"
)

type Querier interface {
	CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error)
	GetPersonByUsername(ctx context.Context, username string) (Person, error)
	UpdateCredit(ctx context.Context, arg UpdateCreditParams) error
}

var _ Querier = (*Queries)(nil)
